openapi: 3.0.3
info:
  title: CardService API
  description: A Spring Boot application with REST API for storing, requesting and validating debit cards. This application is connected to an Oracle SQL server for storing card data.
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Running as standalone application on local computer
tags:
  - name: card-rest-controller
    description: REST API for managing debit cards
paths:
  /ecards/:
    post:
      tags:
        - card-rest-controller
      summary: Create new card
      description: Create a new card and save it in the database. This command also automatically generates a hash for the card based on the input data, which can be used for validation later.
      operationId: createCardUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestCardReq'
      responses:
        '200':
          description: OK - This code appears if everything went correctly and the card was created succesfully.
        '500':
          description: Internal server error - This code appears if something went wrong during the card creating process - A deatiled error message can be seen in the message section.
  /ecards/validate:
    post:
      tags:
        - card-rest-controller
      summary: Validate card
      description: This command uses the card data provided in the request body to find a card in the database. If a card is found, a hash will be calculated from the input data which will be compared to the one in the database. This command will return a VALID response if the provided card type AND the calculated hash matches with the one associated with the card in the database, AND if the card is not disabled. If ANY of these requirements are not met, the command will return an INVALID response.
      operationId: validateCardUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestCardVal'
      responses:
        '200':
          description: OK - This code appears if the card was found in the database and the validation process was finished. The result of the validation (VALID/INVALID) can be seen in the response.
          content:
            '*/*':
              schema:
                type: string
        '500':
          description: Internal server error - This code appears if the requested card was not found, or if something went wrong during the validation process. - A detailed error message can be seen in the message section.
  '/ecards/{cardNumber}':
    get:
      tags:
        - card-rest-controller
      summary: Request a card by card number
      description: This command performs a search in the database to find a card using the card nubmer given in the input. If found, it returns all available information about the card in response.
      operationId: requestCardUsingGET
      parameters:
        - name: cardNumber
          in: path
          description: The requested card number. Only digits allowed, without separation characters.
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK - This code appears if the requested card was found. The response body contains all the information available for that card.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RestCardRes'
        '404':
          description: Not found - This code appears if a card using the requested card number was not found in the database.
    put:
      tags:
        - card-rest-controller
      summary: Disable a card
      description: This command performs a search in the database to find a card using the card nubmer given in the input. If found, it will mark the card as disabled, which will make any attempt to validate the card (even with correct data) to fail. Once a card is disabled, it CAN NOT be enabled again through the API.
      operationId: disableCardUsingPUT
      parameters:
        - name: cardNumber
          in: path
          description: The number of the card to be disabled. Only digits allowed, without separation characters.
          required: true
          style: simple
          schema:
            type: string
      responses:
        '200':
          description: OK - This code appears if the requested card was found. The response body contains all the information available for that card.
        '404':
          description: Not found - This code appears if a card using the requested card number was not found in the database.
components:
  schemas:
    RestCardReq:
      title: New card input format
      type: object
      properties:
        CVV:
          type: string
        cardNumber:
          type: string
        cardType:
          type: string
        contactInfo:
          type: array
          items:
            $ref: '#/components/schemas/RestContact'
        owner:
          type: string
        validThru:
          type: string
    RestCardRes:
      title: Requested card format
      type: object
      properties:
        cardNumber:
          type: string
        cardType:
          type: string
        contactInfo:
          type: array
          items:
            $ref: '#/components/schemas/RestContact'
        disabled:
          type: boolean
        owner:
          type: string
        validThru:
          type: string
    RestCardVal:
      title: Card data format for validation
      type: object
      properties:
        CVV:
          type: string
        cardNumber:
          type: string
        cardType:
          type: string
        validThru:
          type: string
    RestContact:
      title: Contact list format
      type: object
      properties:
        contact:
          type: string
        type:
          type: string
